# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/Modeltech_pe_edu_10.4a/win32pe_edu
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir g:/zynq_project/repo/managed_ip_project/managed_ip_project.tmp/camera2640_module_v1_0_v1_0_project/camera2640_module_v1_0_v1_0_project.cache/wt [current_project]
set_property parent.project_path g:/zynq_project/repo/managed_ip_project/managed_ip_project.tmp/camera2640_module_v1_0_v1_0_project/camera2640_module_v1_0_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths g:/zynq_project/repo/camera2640_module_1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet g:/zynq_project/repo/managed_ip_project/managed_ip_project.tmp/camera2640_module_v1_0_v1_0_project/camera2640_module_v1_0_v1_0_project.runs/frame_fifo_synth_1/frame_fifo.dcp
set_property used_in_implementation false [get_files g:/zynq_project/repo/managed_ip_project/managed_ip_project.tmp/camera2640_module_v1_0_v1_0_project/camera2640_module_v1_0_v1_0_project.runs/frame_fifo_synth_1/frame_fifo.dcp]
read_verilog -library xil_defaultlib G:/zynq_project/hdl/edge_detector.v
read_vhdl -library xil_defaultlib {
  G:/zynq_project/hdl/i2cm.vhd
  G:/zynq_project/hdl/ov2640reg_rom.vhd
  G:/zynq_project/hdl/camera_init.vhd
  G:/zynq_project/hdl/capture_frame.vhd
  G:/zynq_project/hdl/camera2640.vhd
  g:/zynq_project/repo/camera2640_module_1.0/hdl/camera2640_module_v1_0_m_axis.vhd
  g:/zynq_project/repo/camera2640_module_1.0/hdl/camera2640_module_v1_0.vhd
}
synth_design -top camera2640_module_v1_0 -part xc7z020clg484-1
write_checkpoint -noxdef camera2640_module_v1_0.dcp
catch { report_utilization -file camera2640_module_v1_0_utilization_synth.rpt -pb camera2640_module_v1_0_utilization_synth.pb }
