# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frame_fifo || ORIG_REF_NAME==frame_fifo}]

# XDC: g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo/frame_fifo_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frame_fifo || ORIG_REF_NAME==frame_fifo}] {/U0 }]/U0 ]]

# XDC: g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo/frame_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frame_fifo || ORIG_REF_NAME==frame_fifo}] {/U0 }]/U0 ]]
