# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo.xci
# IP: The module: 'frame_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo/frame_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo/frame_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo.xci
# IP: The module: 'frame_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo/frame_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo/frame_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
