# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/Modeltech_pe_edu_10.4a/win32pe_edu
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir g:/zynq_project/repo/managed_ip_project/managed_ip_project.tmp/camera2640_module_v1_0_v1_0_project/camera2640_module_v1_0_v1_0_project.cache/wt [current_project]
set_property parent.project_path g:/zynq_project/repo/managed_ip_project/managed_ip_project.tmp/camera2640_module_v1_0_v1_0_project/camera2640_module_v1_0_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths g:/zynq_project/repo/camera2640_module_1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo.xci
set_property used_in_implementation false [get_files -all g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo.dcp]
set_property is_locked true [get_files g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top frame_fifo -part xc7z020clg484-1 -mode out_of_context
rename_ref -prefix_all frame_fifo_
write_checkpoint -noxdef frame_fifo.dcp
catch { report_utilization -file frame_fifo_utilization_synth.rpt -pb frame_fifo_utilization_synth.pb }
if { [catch {
  file copy -force g:/zynq_project/repo/managed_ip_project/managed_ip_project.tmp/camera2640_module_v1_0_v1_0_project/camera2640_module_v1_0_v1_0_project.runs/frame_fifo_synth_1/frame_fifo.dcp g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir g:/zynq_project/repo/managed_ip_project/managed_ip_project.tmp/camera2640_module_v1_0_v1_0_project/camera2640_module_v1_0_v1_0_project.ip_user_files/ip/frame_fifo]} {
  catch { 
    file copy -force g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo_stub.v g:/zynq_project/repo/managed_ip_project/managed_ip_project.tmp/camera2640_module_v1_0_v1_0_project/camera2640_module_v1_0_v1_0_project.ip_user_files/ip/frame_fifo
  }
}

if {[file isdir g:/zynq_project/repo/managed_ip_project/managed_ip_project.tmp/camera2640_module_v1_0_v1_0_project/camera2640_module_v1_0_v1_0_project.ip_user_files/ip/frame_fifo]} {
  catch { 
    file copy -force g:/zynq_project/repo/camera2640_module_1.0/src/frame_fifo/frame_fifo_stub.vhdl g:/zynq_project/repo/managed_ip_project/managed_ip_project.tmp/camera2640_module_v1_0_v1_0_project/camera2640_module_v1_0_v1_0_project.ip_user_files/ip/frame_fifo
  }
}
